[package]
name = "libdd-dogstatsd-client"
version= "1.0.0"
description = "A dogstatsd client for sending metrics to a dogstatsd server."
homepage = "https://github.com/DataDog/libdatadog/tree/main/libdd-dogstatsd-client"
repository = "https://github.com/DataDog/libdatadog/tree/main/libdd-dogstatsd-client"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
ddcommon = { version = "1.0.0", path = "../libdd-common", package = "libdd-common", default-features = false }
cadence = "1.3.0"
serde = { version = "1.0", features = ["derive", "rc"] }
tracing = { version = "0.1", default-features = false }
anyhow = { version = "1.0" }
http = "1.0"

[features]
default = ["https"]
https = ["ddcommon/https"]


[dev-dependencies]
tokio = {version = "1.23", features = ["rt", "time", "test-util", "rt-multi-thread"], default-features = false}
