# Copyright 2026-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[package]
name = "libdd-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
libdd-capabilities = { path = "../libdd-capabilities" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libdd-common = { path = "../libdd-common" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
capabilities = { git = "https://github.com/DataDog/libdatadog-nodejs.git", branch = "jwiriath/libdatadog-wasm-effort" }
