# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2021-Present Datadog, Inc.

[package]
name = "libdd-live-debugger-ffi"
version = "1.0.0"
repository = "https://github.com/DataDog/libdatadog/tree/main/libdd-live-debugger-ffi"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
bench = false

[dependencies]
libdd-live-debugger = { path = "../libdd-live-debugger" }
libdd-common = { path = "../libdd-common" }
libdd-common-ffi = { path = "../libdd-common-ffi", default-features = false }
percent-encoding = "2.1"
uuid = { version = "1.7.0", features = ["v4"] }
serde_json = "1.0"
tokio = "1.36.0"
tokio-util = { version = "0.7", features = ["rt"] }
log = "0.4.21"

[features]
default = ["cbindgen"]
cbindgen = ["build_common/cbindgen", "libdd-common-ffi/cbindgen"]

[build-dependencies]
build_common = { path = "../build-common" }
