[package]
name = "libdd-trace-normalization-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
libdd-trace-normalization = { path = "..", features = ["fuzzing"] }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "fuzz_normalize_span"
path = "fuzz_targets/fuzz_normalize_span.rs"
test = false
doc = false

