# Copyright 2025-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

language = "C"
cpp_compat = true
tab_width = 2
header = """// Copyright 2025-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0
"""
include_guard = "DDOG_FFE_H"
style = "both"
pragma_once = true

no_includes = true
sys_includes = ["stdbool.h", "stddef.h", "stdint.h"]
includes = ["common.h"]

[export]
include = ["datadog-ffe-ffi"]
prefix = "ddog_ffe_"
renaming_overrides_prefixing = true

[export.rename]
"Error" = "ddog_Error"
"Vec_U8" = "ddog_Vec_U8"
"ArrayMap_BorrowedStr__BorrowedStr" = "ddog_ffe_ArrayMap_BorrowedStr"
"KeyValue_BorrowedStr__BorrowedStr" = "ddog_ffe_KeyValue_BorrowedStr"

[export.mangle]
rename_types = "PascalCase"

[enum]
prefix_with_name = true
rename_variants = "ScreamingSnakeCase"

[fn]
must_use = "DDOG_CHECK_RETURN"

[parse]
parse_deps = true
include = ["libdd-common-ffi", "datadog-ffe"]
