# Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

language = "C"
cpp_compat = true
tab_width = 2
header = """// Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0
"""
include_guard = "DDOG_CRASHTRACKER_H"
style = "both"
pragma_once = true

no_includes = true
sys_includes = ["stdbool.h", "stddef.h", "stdint.h"]
includes = ["common.h"]
after_includes = """

#if defined(_WIN32) && defined(_CRASHTRACKING_COLLECTOR)
#include <werapi.h>
#include <windows.h>
#endif

"""

[defines]
"target_os = windows" = "_WIN32"
"feature = collector_windows" = "_CRASHTRACKING_COLLECTOR"

[export]
prefix = "ddog_crasht_"
renaming_overrides_prefixing = true

[export.rename]
"BOOL" = "BOOL"
"ByteSlice" = "ddog_ByteSlice"
"CancellationToken" = "ddog_CancellationToken"
"CharSlice" = "ddog_CharSlice"
"Endpoint" = "ddog_Endpoint"
"Error" = "ddog_Error"
"HMODULE" = "HMODULE"
"HRESULT" = "HRESULT"
"HttpStatus" = "ddog_HttpStatus"
"Option_U32" = "ddog_Option_U32"
"Slice_CChar" = "ddog_Slice_CChar"
"Slice_I64" = "ddog_Slice_I64"
"Slice_U8" = "ddog_Slice_U8"
"Tag" = "ddog_Tag"
"Timespec" = "ddog_Timespec"
"Vec_Tag" = "ddog_Vec_Tag"
"Vec_U8" = "ddog_Vec_U8"
"VoidResult" = "ddog_VoidResult"
"StringWrapper" = "ddog_StringWrapper"
"StringWrapperResult" = "ddog_StringWrapperResult"
"CrashInfoBuilderNewResult" = " ddog_crasht_CrashInfoBuilder_NewResult"
"StackTraceNewResult" = " ddog_crasht_StackTrace_NewResult"
"StackFrameNewResult" = "ddog_crasht_StackFrame_NewResult"
"CrashInfoNewResult" = "ddog_crasht_CrashInfo_NewResult"
"WER_RUNTIME_EXCEPTION_INFORMATION" = "WER_RUNTIME_EXCEPTION_INFORMATION"

[export.mangle]
rename_types = "PascalCase"

[enum]
prefix_with_name = true
rename_variants = "ScreamingSnakeCase"

[fn]
must_use = "DDOG_CHECK_RETURN"

[parse]
parse_deps = true
include = ["libdd-common", "libdd-common-ffi", "libdd-crashtracker", "ux"]
exclude = ["libdd_crashtracker::crash_info::cxx"]
