[package]
name = "libdd-ddsketch"
version = "1.0.0"
description = "Minimal implementation of Datadog's DDSketch"
homepage = "https://github.com/DataDog/libdatadog/tree/main/libdd-ddsketch"
repository = "https://github.com/DataDog/libdatadog/tree/main/libdd-ddsketch"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.13.5"

[build-dependencies]
prost-build = { version = "0.13.5", optional = true  }
protoc-bin-vendored = { version = "3.0.0", optional = true }

[features]
generate-protobuf = ["dep:prost-build", "dep:protoc-bin-vendored"]

[lib]
bench = false
