[package]
name = "libdd-libunwind"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
links = "unwind"  # Tells Cargo this crate links to libunwind (prevents multiple builds)

[lib]
crate-type = ["lib"]
bench = false

[dependencies]
paste = "1.0"
libc = "0.2"

[build-dependencies]
cc = "1.0"
