[package]
name = "libdd-trace-protobuf"
version = "1.0.0"
authors = ["David Lee <david.lee@datadoghq.com>"]
description = "Protobuf utils for Datadog's traces serialization"
homepage = "https://github.com/DataDog/libdatadog/tree/main/libdd-trace-protobuf"
repository = "https://github.com/DataDog/libdatadog/tree/main/libdd-trace-protobuf"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
prost = "0.13.5"
serde = { version = "1.0.145", features = ["derive"] }
serde_bytes = "0.11.9"

[build-dependencies]
prost-build = { version = "0.13.5", optional = true  }
protoc-bin-vendored = { version = "3.0.0", optional = true }

[features]
generate-protobuf = ["dep:prost-build", "dep:protoc-bin-vendored"]

[dev-dependencies]
serde_json = "1.0.117"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
