[package]
name = "libdd-live-debugger"
version = "1.0.0"
description = "A Rust library for dynamic runtime instrumentation that captures snapshots, metrics, and trace data via remotely-configured probes."
repository = "https://github.com/DataDog/libdatadog/tree/main/libdd-live-debugger"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow = "1.0"
libdd-common = { path = "../libdd-common" }
libdd-data-pipeline = { path = "../libdd-data-pipeline" }
hyper = { workspace = true}
http-body-util = "0.1"

regex = "1.9.3"
percent-encoding = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sys-info = { version = "0.9.0" }
uuid = { version = "1.0", features = ["v4"] }
regex-automata = "0.4.5"
smallvec = "1.13.2"
constcat = "0.4.1"
tokio = "1.36.0"

[lib]
bench = false
