[package]
name = "libdd-trace-stats"
version = "1.0.0"
description = "This crate provides utilities to compute stats from Datadog traces."
homepage = "https://github.com/DataDog/libdatadog/tree/main/libdd-trace-stats"
repository = "https://github.com/DataDog/libdatadog/tree/main/libdd-trace-stats"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
autobenches = false

[dependencies]
libdd-ddsketch = { version = "1.0.0", path = "../libdd-ddsketch" }
libdd-trace-protobuf = { version = "1.0.0", path = "../libdd-trace-protobuf" }
libdd-trace-utils = { version = "1.0.0", path = "../libdd-trace-utils", default-features = false }
hashbrown = { version = "0.15" }

[lib]
bench = false

[[bench]]
name = "main"
harness = false
path = "benches/main.rs"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"
