# Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[package]
name = "libdd-profiling"
version = "1.0.0"
description = "Continuous profiling library supporting pprof format collection and export to Datadog"
homepage = "https://github.com/DataDog/libdatadog/tree/main/libdd-profiling"
repository = "https://github.com/DataDog/libdatadog/tree/main/libdd-profiling"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autobenches = false

[lib]
crate-type = ["lib"]
bench = false

[[bench]]
name = "main"
harness = false

[dependencies]
allocator-api2 = { version = "0.2", default-features = false, features = ["alloc"] }
anyhow = "1.0"
bitmaps = "3.2.0"
byteorder = { version = "1.5", features = ["std"] }
bytes = "1.1"
chrono = {version = "0.4", default-features = false, features = ["std", "clock"]}
crossbeam-utils = { version = "0.8.21" }
libdd-alloc = { version = "1.0.0", path = "../libdd-alloc" }
libdd-profiling-protobuf = { version = "1.0.0", path = "../libdd-profiling-protobuf", features = ["prost_impls"] }
libdd-common = { version = "1.0.0", path = "../libdd-common" }
hashbrown = { version = "0.16", default-features = false }
http = "1.0"
indexmap = "2.11"
lz4_flex = { version = "0.9", default-features = false, features = ["std", "safe-encode", "frame"] }
mime = "0.3.16"
parking_lot = { version = "0.12", default-features = false }
prost = "0.13.5"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "multipart", "rustls-tls", "json"] }
rustc-hash = { version = "1.1", default-features = false }
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
target-triple = "0.1.4"
thiserror = "2"
zstd = { version = "0.13", default-features = false }

[dev-dependencies]
bolero = "0.13"
criterion = "0.5.1"
lz4_flex = { version = "0.9", default-features = false, features = ["std", "frame"] }
proptest = "1"
