[package]
name = "datadog-trace-stats"
description = "This crate provides utilities to compute stats from traces."
rust-version.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
autobenches = false

[dependencies]
libdd-ddsketch = { version = "1.0.0", path = "../libdd-ddsketch" }
datadog-trace-protobuf = { path = "../datadog-trace-protobuf" }
datadog-trace-utils = { path = "../datadog-trace-utils", default-features = false }
hashbrown = { version = "0.15" }

[lib]
bench = false

[[bench]]
name = "main"
harness = false
path = "benches/main.rs"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"
