# Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
# SPDX-License-Identifier: Apache-2.0

[package]
name = "tools"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
bench = false

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
colored = "2"
regex = "1"
wait-timeout = "0.2"

[[bin]]
name = "dedup_headers"
bench = false

[[bin]]
name = "ffi_test"
bench = false
