[package]
name = "libdd-tracer-flare"
version = "1.0.0"
description = "Rust library for collecting and transmitting Datadog tracer diagnostic flares via remote configuration."
rust-version.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
autobenches = false
publish = false
authors.workspace = true
homepage = "https://github.com/DataDog/libdatadog/tree/main/libdd-tracer-flare"
repository = "https://github.com/DataDog/libdatadog/tree/main/libdd-tracer-flare"

[dependencies]
anyhow = "1.0"
datadog-remote-config = { path = "../datadog-remote-config", default-features = false }
libdd-common = { version = "1.0.0", path = "../libdd-common" }
libdd-trace-utils = { version = "1.0.0", path = "../libdd-trace-utils" }
hyper = { workspace = true}
tokio = { version = "1.36.0", features = ["time"] }
serde_json = "1.0"
zip = "4.0.0"
walkdir = "2.4"
tempfile = "3.8"

[lib]
bench = false

[dev-dependencies]
datadog-remote-config = { path = "../datadog-remote-config", features = ["test"] }

[features]
default = ["listener"]
listener = ["datadog-remote-config/client"]
