[package]
edition = "2021"
license = "Apache 2.0"
name = "datadog-sidecar-macros"
version = "0.0.1"

[lib]
proc-macro = true
bench = false

[dependencies]
syn = { version = "^2", features = ["full"] }
quote = "^1"
